package com.devoler.aicup2.view;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

public final class Launcher {
	private static final String[] TEST_TRACKS = {
			"1 LLLUUUURRRRRRDDDDLLL",
			"3 RRRRRRRRRRRRRRRRRRUUUUUUUUUUUUUUUUULLLLLLLLLLLLLLLLLLLLLLLLLLLDDDDDDDDDDDDDDDDDRRRRRRRRR",
			"1 DDDDDDDDDDDLDLDLDLDLDLLDLDLDLDLLUUUULUUUUUUUUULUUUUUUUUULUUUUURRRDRRRRDRRRRRRDRRDDDD",
			"0 LLLLULLULLULLULLULLULLURRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDDLLDLLDLLDLLDLLDLLLLL",
			"3 UUUUUUUUULUUUUUUUUUUUUUUUUUULUUUUUUUUUUULLULLLULLLLDDDDDDDDDDDDDDLLLLDDDLLLLLLDLDDLDLDDLDDLDLDDLDDLDLDDLDDLDLDDLDDLDLDDLDRDRRDRDRRDRRDRDRRDRRDRDRRDRDLDDDLDDDLDDDLDDDLDDDLDDDLDDDLDDDDRDDDDDDRDDDDDDRDDDDDDRDDDRRUURURUUUUUUUURRRRRUUUUUUUUUUUUUUUUUURUUUUUUUURUUUUURUUUURRRRRRRRDRDDRDDRDDDRDDRDDRDDRDDRDDDRDDRDDRDRRURRRRURRRRURRRURRRRURRUUUURUUUUUUURUUUUUUUURUUUULULULLULULLULULLDLDLLDLLDLDLLLLLLLLLLLULULUUUUUUUU",
			"1 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDLDDDLDDDDLDDLDLDLDLDLDLDLDLDLDLDLLDLLDLLLLDLLLLLLDLLLLLLLLLLULLLLLLLLLLLLLLLULLLLLLLLULULULLULULLULULULLULULULUULUUUULUUUUULUULULULULDDLDDDLDDDDLDDDRDRDDRDRDRDRDRDRDRDRDRRDRDRDRDRDRDRRRDRRDRDRRDRRRDRRRDRRRRDRRRDRRRRDRRRDRRRDRRDRDDDRDDDLDDDLDLDLLLDLLLDLLLLLLLLULLLLLLLULUUULUULUULUUULULULULULULULLULULULULULLULULULULLULULULULULLULULULULULUUULUUUUULUUUUULUUUUURUUUURUUUURUURURRURRURRDDDLDDLDLDLDDDRRRRRUURRRRRRRRRDRRRRRRRDRRRRRRRDRRRRRRRDRRRRRRRDRRRRRRRDRRRRURRURRURUURUUURUUULUULUUULULULULULULULULLULLLULLLLULLLULLLULLLLLLLLULLLLLLLLULLLLLULLLLLULLLULULULULULULULULUULULUULUUUULUUUUULUUUUUUUUULUUUUUUUUUUUURUUUUUUUUUURUUUUUURUURUURUURUURUURUURURURURURURURURURRURRRURRURRURRRRRRRRURRRRRRRRRRRDRRRRRRRRDRRRRRRRRRDRRRRRRRRRDRRRRRRRDRRRRRRDRRRRRRDRRRRRRDRRRRRRDRRRRRRDRRRRRRRDRRRRRRRDRRRDLLLDLDLLLLLLLLLLLLDLLLLDLLDLLDLDLDLDLDDDDDLDDDDDDDDDLDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD" };

	private static final String TRACK = "2 RRRRUUUUUULLLLLLLLDDDDDDRRRR";
	private static final String SOLUTION = "RLRLRLRLUDUDUDUDUDUDLRLRLRLRLRLRLRLRDUDUDUDUDUDURLRR";
	
	public static void main(String[] args) {
		JFrame frame = new JFrame("Launcher");
		JPanel allImages = new JPanel();
		allImages.getInsets().set(5, 5, 5, 5);
		allImages.setLayout(new BoxLayout(allImages, BoxLayout.PAGE_AXIS));
		allImages.add(Box.createVerticalStrut(10));
		for(String testTrack: TEST_TRACKS) {
			allImages.add(new RaceTrackPanel(testTrack));
			allImages.add(Box.createVerticalStrut(10));
		}
		allImages.revalidate();
		JScrollPane scrollPane = new JScrollPane(allImages, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
		frame.getContentPane().add(scrollPane);
		frame.pack();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		Utils.centerWindow(frame);
		frame.setVisible(true);
	}

}
